# Generated by Django 4.0.4 on 2023-03-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30)),
                ('cantidad_disponible', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
