# Generated by Django 4.0.4 on 2023-03-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_del_producto',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagenes'),
        ),
    ]
